{{- if and (not .Values.api.secret.existingSecretName) (not .Values.api.secret.externalSecret.enabled) (not .Values.api.secret.sealedSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: ml-air-api-secrets
type: Opaque
stringData:
  {{ .Values.api.secret.key }}: {{ .Values.api.secret.value | quote }}
{{- end }}
