{{- if .Values.api.secret.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ml-air-api-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.api.secret.externalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.api.secret.externalSecret.secretStoreRef.kind | quote }}
  target:
    name: ml-air-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.api.secret.key | quote }}
      remoteRef:
        key: {{ .Values.api.secret.externalSecret.remoteRef.key | quote }}
        {{- if .Values.api.secret.externalSecret.remoteRef.property }}
        property: {{ .Values.api.secret.externalSecret.remoteRef.property | quote }}
        {{- end }}
{{- end }}
