{{- if .Values.api.secret.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ml-air-api-secrets
spec:
  encryptedData:
    {{ .Values.api.secret.key }}: {{ .Values.api.secret.sealedSecret.encryptedData | quote }}
  template:
    metadata:
      name: ml-air-api-secrets
    type: Opaque
{{- end }}
