{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-air
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ml-air-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: ml-air-api
                port:
                  number: {{ .Values.api.service.port }}
{{- end }}
