import {
  BarChart3,
  Box,
  Database,
  GitBranch,
  History,
  LayoutDashboard,
  ListTodo,
  Moon,
  Network,
  Play,
  Route,
  Search,
  Settings,
  Sparkles,
  Sun,
  Bot,
  DollarSign,
  FileText,
  FlaskConical,
} from "lucide-react"

import type { PaletteCommandDef } from "./types"

export const PALETTE_COMMANDS: PaletteCommandDef[] = [
  {
    id: "nav-dashboard",
    section: "navigation",
    kind: "nav",
    label: "Dashboard",
    description: "Operations overview and KPIs",
    keywords: ["home", "overview", "bento"],
    href: "/dashboard",
    icon: LayoutDashboard,
    shortcut: "D",
    pinnable: true,
  },
  {
    id: "nav-search",
    section: "navigation",
    kind: "nav",
    label: "Search",
    description: "Full-text search across resources",
    keywords: ["find", "query"],
    href: "/search",
    icon: Search,
    shortcut: "/",
    pinnable: true,
  },
  {
    id: "nav-datasets",
    section: "navigation",
    kind: "nav",
    label: "Datasets",
    description: "Dataset hub and versions",
    href: "/datasets",
    icon: Database,
    shortcut: "S",
    pinnable: true,
  },
  {
    id: "nav-lifecycle",
    section: "navigation",
    kind: "nav",
    label: "Lifecycle",
    description: "Semantic audit and promotions",
    href: "/lifecycle",
    icon: History,
    shortcut: "L",
    pinnable: true,
  },
  {
    id: "nav-models",
    section: "navigation",
    kind: "nav",
    label: "Models",
    description: "Model registry and versions",
    href: "/models",
    icon: Box,
    shortcut: "M",
    pinnable: true,
  },
  {
    id: "nav-lineage",
    section: "navigation",
    kind: "nav",
    label: "Lineage",
    description: "Artifact lineage graph",
    href: "/lineage",
    icon: Network,
    shortcut: "G",
    pinnable: true,
  },
  {
    id: "nav-pipelines",
    section: "navigation",
    kind: "nav",
    label: "Pipelines",
    description: "Pipeline definitions and versions",
    keywords: ["workflow", "dag"],
    href: "/pipelines",
    icon: GitBranch,
    shortcut: "P",
    pinnable: true,
    visible: ({ showExecutionNav }) => showExecutionNav,
  },
  {
    id: "nav-runs",
    section: "navigation",
    kind: "nav",
    label: "Runs",
    description: "Execution runs and status",
    href: "/runs",
    icon: Play,
    shortcut: "R",
    pinnable: true,
    visible: ({ showExecutionNav }) => showExecutionNav,
  },
  {
    id: "nav-tasks",
    section: "navigation",
    kind: "nav",
    label: "Tasks",
    description: "Tasks from recent runs",
    href: "/tasks",
    icon: ListTodo,
    shortcut: "T",
    pinnable: true,
    visible: ({ showExecutionNav }) => showExecutionNav,
  },
  {
    id: "nav-traces",
    section: "navigation",
    kind: "nav",
    label: "Traces",
    description: "Distributed trace viewer",
    href: "/traces",
    icon: Route,
    pinnable: true,
    visible: ({ showExecutionNav }) => showExecutionNav,
  },
  {
    id: "nav-ai-gateway",
    section: "navigation",
    kind: "nav",
    label: "AI Gateway",
    description: "Unified LLM routing and providers",
    href: "/ai-gateway",
    icon: Bot,
    pinnable: true,
  },
  {
    id: "nav-billing",
    section: "navigation",
    kind: "nav",
    label: "Billing",
    description: "Usage chargeback and snapshots",
    href: "/billing",
    icon: DollarSign,
    pinnable: true,
  },
  {
    id: "nav-prompts",
    section: "navigation",
    kind: "nav",
    label: "Prompts",
    description: "Prompt versions and deployment",
    href: "/prompts",
    icon: FileText,
    pinnable: true,
  },
  {
    id: "nav-copilot",
    section: "navigation",
    kind: "nav",
    label: "Copilot",
    description: "Hub AI assistant",
    href: "/copilot",
    icon: Sparkles,
    pinnable: true,
  },
  {
    id: "nav-automl",
    section: "navigation",
    kind: "nav",
    label: "AutoML",
    description: "Hyperparameter search jobs",
    href: "/automl",
    icon: FlaskConical,
    pinnable: true,
  },
  {
    id: "nav-settings",
    section: "navigation",
    kind: "nav",
    label: "Settings",
    description: "Workspace, tokens, and plugins",
    href: "/settings/profile",
    icon: Settings,
    shortcut: ",",
    pinnable: true,
  },
  {
    id: "action-metrics",
    section: "actions",
    kind: "action",
    label: "Semantic metrics index",
    description: "Lifecycle metrics and Grafana dashboards",
    href: "/lifecycle?metrics=1",
    icon: BarChart3,
    pinnable: true,
  },
  {
    id: "action-lifecycle",
    section: "actions",
    kind: "action",
    label: "Lifecycle timeline",
    description: "Readiness, train, and promote events",
    href: "/lifecycle",
    icon: History,
    pinnable: true,
  },
  {
    id: "action-datasets",
    section: "actions",
    kind: "action",
    label: "Open Dataset Hub",
    description: "Browse datasets and training entry points",
    href: "/datasets",
    icon: Database,
    pinnable: true,
  },
  {
    id: "action-train",
    section: "actions",
    kind: "action",
    label: "Train model",
    description: "Start from a dataset version",
    href: "/datasets",
    icon: Play,
    pinnable: true,
  },
  {
    id: "action-search",
    section: "actions",
    kind: "action",
    label: "Open search page",
    description: "Advanced filters and result tables",
    href: "/search",
    icon: Search,
    pinnable: true,
  },
  {
    id: "appearance-light",
    section: "appearance",
    kind: "appearance",
    label: "Use light theme",
    description: "Switch to light appearance",
    icon: Sun,
    run: ({ setTheme }) => setTheme("light"),
  },
  {
    id: "appearance-dark",
    section: "appearance",
    kind: "appearance",
    label: "Use dark theme",
    description: "Switch to dark appearance",
    icon: Moon,
    run: ({ setTheme }) => setTheme("dark"),
  },
  {
    id: "appearance-settings",
    section: "appearance",
    kind: "appearance",
    label: "Open settings",
    description: "Tokens, scope, and operator preferences",
    href: "/settings/profile",
    icon: Settings,
  },
]

export function visiblePaletteCommands(ctx: { showExecutionNav: boolean }): PaletteCommandDef[] {
  return PALETTE_COMMANDS.filter((cmd) => cmd.visible?.(ctx) !== false)
}
